# Generated by Django 5.2.9 on 2026-01-09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zerver", "0780_puppet_handlers"),
    ]

    operations = [
        # Create UserPersona model
        migrations.CreateModel(
            name="UserPersona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("avatar_url", models.URLField(blank=True, max_length=500, null=True)),
                ("color", models.CharField(blank=True, default=None, max_length=10, null=True)),
                ("bio", models.TextField(blank=True, default="", max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "name")},
            },
        ),
        # Add persona fields to Message (via AbstractMessage)
        migrations.AddField(
            model_name="message",
            name="persona",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zerver.userpersona",
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="persona_display_name",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="persona_avatar_url",
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="persona_color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        # Add same fields to ArchivedMessage
        migrations.AddField(
            model_name="archivedmessage",
            name="persona",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="zerver.userpersona",
            ),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="persona_display_name",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="persona_avatar_url",
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="archivedmessage",
            name="persona_color",
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
